### ISSUE TITLE
ネットワーク切り替え時にアプリが落ちる

### ISSUE THREAD

**Issue by Na0ki** [shibafu528/Yukari#172]
## 概要
タイトルの通りネットワーク切り替え時にアプリが落ちました。
WiFi -> LTE, LTE -> WiFi のどちらのパターンでも再現しました。
なお、必ず発生するわけではなく頻度にばらつきがあるものの10数回試して3,4回程度発生しました。

## 再現手順
WiFi接続状態でアプリを立ち上げ、LTEに切り替える。
LTE接続状態でアプリを立ち上げ、WiFiに切り替える。

## 環境
|||
|:------|:------|
|端末|Huawei P9|
|OS|Android 7.0|
|アプリVer|2.1.0.1610-dev (linkage 180827 bcb8fb3)|

**Comment by shibafu528** [comment]
Yukari Next 2.1.0.1667-dev (linkage 181021 fcaf1f7) にて修正版をリリースしました。
