### ISSUE TITLE
F-Droid inclusion?

### ISSUE THREAD

**Issue by IzzySoft** [shibafu528/Yukari#180]
Just wanted to ask if you'd like to have your app available via the free, open-source F-Droid "store". From what I've seen, that would be the perfect place for your app – so I took the freedom to [open an RFP](https://gitlab.com/fdroid/rfp/issues/704) (Request For Packaging) there.

**Comment by licaon-kter** [comment]
But these need fixing first: https://gitlab.com/fdroid/rfp/issues/704#note_98376465

**Comment by shibafu528** [comment]
Thank you for your suggestion. Unfortunately, I would like to decline that.  
Because I can't afford to fix the problem to meet the requirements for F-Droid.

**Comment by IzzySoft** [comment]
That's a pity, @shibafu528 – but would you at least consider attaching the APK with the `releases/`, so they can be grabbed without the need of Playstore?

**Comment by IzzySoft** [comment]
Just one last "bump": if you'd attach the APK, I could (automatically) grab it for [my repo](https://apt.izzysoft.de/fdroid), which is less restrictive than the official one. Please let me know when you do so.
