### ISSUE TITLE
文章に草を生やす機能が 1 char 以上で構成される文字を壊す

### ISSUE THREAD

**Issue by kb10uy** [shibafu528/Yukari#214]
https://mstdn.maud.io/@kb10uy/101746027854760988

char 単位で挿入しているせいっぽそうな雰囲気。
例によって Grapheme Cluster 単位の処理を導入する必要がありそうだが、そもそもこれ使ってる人いるのか…？

**Comment by shibafu528** [comment]
原因はその通りで、かなり古いバージョンから潜在している不具合かと思われます。

しかし使っている人いるんですかね……こんな影の薄いアサインの機能……

https://github.com/shibafu528/Yukari/blob/b4280a3ecd04901245f56c42bff6ef60e526c8c7/Yukari/src/main/java/shibafu/yukari/activity/TweetActivity.java#L727-L749
