### ISSUE TITLE
共有時にActivityが残らないようにする

### ISSUE THREAD

**Issue by Na0ki** [shibafu528/Yukari#227]
共有機能を使用時にy4aNの投稿Activityが残るが、できれば消えるようにしたいのですがどうでしょうか。

**Comment by Na0ki** [comment]
#228

**Comment by shibafu528** [comment]
詳細な操作手順を教えていただけますか？

(どんなアプリの共有機能から立ち上げて、どう操作していったら残るかとかそんな感じで……)

**Comment by Na0ki** [comment]
まず最初に先のPRを腐ってるので修正します（すみません）
再現方法は以下の通りです。

1. Googleのニュースアプリを開く
1. 任意の記事を開く
1. 画面右上の3点メニューから「共有」を選択
1. ya4Nを選ぶ
1. 投稿する

以上の動作をした場合に投稿画面がタスクスイッチャーに残る現象がある。  
なお、すでにy4aNを起動している場合はそれとは別に起動しているらしい。

**Comment by Na0ki** [comment]
修正しました

期待する動作としては、上記共有の手順完了時にタスクスイッチャーに投稿画面が残っていないことです。

**Comment by shibafu528** [comment]
y4a起動済の場合に既存タスクとは別に上がってるのは `android:taskAffinity` の影響ですね。

(もう随分前なので覚えてないですが、起動済の状態で外部から共有で呼んだ時にバックスタックの状態が変になって嫌だったとかでそうしたような気がします)

**Comment by Na0ki** [comment]
なるほどですね。
別タスクとして立ち上げるのは全く問題ないとは思いますが、消えないのがアレかなと思いました。

`excludeFromRecents` は今回のような要件には合いそうな気はします。

**Comment by Na0ki** [comment]
#228 がマージされたので close します。
