### ISSUE TITLE
&nbsp; がそのまま出てくる

### ISSUE THREAD

**Issue by kb10uy** [shibafu528/Yukari#233]
![Screenshot_20190621-073605](https://user-images.githubusercontent.com/2630080/59885820-8a6b3e00-93f7-11e9-99cc-185c630db6e3.png)

https://mastodon.motcha.tech/@mot/102306249302595944

**Comment by shibafu528** [comment]
再現手順をメモしておきます。

1. Android端末でnbspをどこかからコピーしてくる
2. STやy4aNなどのクライアントの投稿欄に貼り付けてトゥート

**Comment by shibafu528** [comment]
https://social.mikutter.hachune.net/@shibafu528/102319511581377196
